# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: 'f4e07bb8e0bf9ca3313ff11892b9991bf6341502882f677a020a1ff1af6e6bc8589721396b48c0acf28df7438d6851dc7e73b2349da6b4296ca4d21308a7ffbb'

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
